

interfering:
	gcc -g -I./../include -o test test.c ./../lib/libwlpdstm.a -lpthread

random:
	g++ -std=c++11 -g -O3 -I./../include -o test_randomrws test_randomrws.cc ./../lib/libwlpdstm.a -lpthread

clean:
	rm ~.o test
